name: HorseHunt
main: cn.lanink.horsehunt.HorseHunt
version: "0.0.2"
api:
  - 1.0.0
load: POSTWORLD
author: "LT_Name"

depend:
  - "MemoriesOfTime-GameCore"
  - "MobPlugin"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"

permissions:
  HorseHunt.command.user:
    default: true
  HorseHunt.command.admin:
    default: op